In [6]:
import numpy as np

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [10]:
np.random.seed(42)

X = np.random.rand(100, 2)

In [11]:
K = 2

In [12]:
centroids = X[:K]
centroids

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

In [15]:
def kmeans_clustering(X, K, centroids):
    labels = np.argmin(np.linalg.norm(X[:, np.newaxis] - centroids, axis=2), axis=1)
    
    while True:
        new_centroids = np.array([X[labels == k].mean(axis=0) for k in range(K)])
        
        print("Old Centroids --> ")
        print(centroids)
        print("New centroids --> ")
        print(new_centroids)
              
        if np.all(centroids == new_centroids):
              break
              
        centroids = new_centroids
              
        labels = np.argmin(np.linalg.norm(X[:, np.newaxis] - centroids, axis=2), axis=1)
        
    return labels, centroids

In [16]:
labels, centroids = kmeans_clustering(X, K, centroids)

Old Centroids --> 
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
New centroids --> 
[[0.19379588 0.70742408]
 [0.61009742 0.38792328]]
Old Centroids --> 
[[0.19379588 0.70742408]
 [0.61009742 0.38792328]]
New centroids --> 
[[0.20255072 0.65926449]
 [0.64460345 0.38577883]]
Old Centroids --> 
[[0.20255072 0.65926449]
 [0.64460345 0.38577883]]
New centroids --> 
[[0.20310912 0.62746368]
 [0.66633382 0.39330509]]
Old Centroids --> 
[[0.20310912 0.62746368]
 [0.66633382 0.39330509]]
New centroids --> 
[[0.19856032 0.60735315]
 [0.67734612 0.40331141]]
Old Centroids --> 
[[0.19856032 0.60735315]
 [0.67734612 0.40331141]]
New centroids --> 
[[0.20138425 0.58464373]
 [0.69201528 0.41328372]]
Old Centroids --> 
[[0.20138425 0.58464373]
 [0.69201528 0.41328372]]
New centroids --> 
[[0.19211515 0.5417242 ]
 [0.70805942 0.44394621]]
Old Centroids --> 
[[0.19211515 0.5417242 ]
 [0.70805942 0.44394621]]
New centroids --> 
[[0.20796281 0.50020749]
 [0.74341601 0.47424874]]
Old Centroids --> 
[