In [1]:
import numpy as np

### NUMPY - ARRAYS

In [3]:
list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
array = np.array(list)

In [8]:
array.shape

(3, 3)

In [11]:
new_array = np.arange(0, 51, 5)
new_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [12]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((5, 9), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.ones((5, 5), dtype=str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [23]:
np.linspace(0, 10, 3) #Linear Space

array([ 0.,  5., 10.])

In [24]:
np.eye(5) #Identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5) #Random Numbers Between 0 & 1

array([0.25793962, 0.3332152 , 0.24222555, 0.70557484, 0.01342498])

In [29]:
np.random.rand(5, 2)

array([[0.45423054, 0.78815177],
       [0.64179971, 0.60913549],
       [0.16542694, 0.99604987],
       [0.55289034, 0.45932948],
       [0.34542583, 0.61528874]])

In [30]:
np.random.randn(5)

array([ 0.82761189,  1.8029269 ,  0.04523565, -0.77487227,  1.01640307])

In [32]:
np.random.randn(3,2)

array([[ 0.32742019,  0.65504342],
       [-0.38520504,  0.66241025],
       [ 1.72912217,  0.7748044 ]])

In [33]:
np.random.randint(5, 50, 10)

array([20, 12, 43, 37,  9, 41, 22,  8,  5,  5])

In [34]:
np.random.randint(5, 50, (2, 5))

array([[49, 37, 14, 49, 24],
       [46, 45, 26,  6, 42]])

In [35]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
arr = np.arange(0, 25)

In [40]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
rndarr = np.random.randint(0, 101, 20)
rndarr

array([ 57,  21,  88,  48,  90,  58,  41,  91,  59,  79,  14,  61,  61,
        46,  61,  50,  54,  63,   2, 100])

In [44]:
rndarr.max()

100

In [45]:
rndarr.min()

2

In [48]:
rndarr.argmax() #Returns index of the Maximum Vaue.

19

In [50]:
rndarr.argmin() #Returns index of the Minimum Vaue.

18

In [51]:
rndarr.dtype

dtype('int32')

### NUMPY - INDEXING & SELECTION

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### BROADCASTING

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0, 11)

In [13]:
slice_of_arr = arr[0:5]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr # The slice of array acts as a pointer to the Original array.

array([99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy[:] = 100

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### 2D ARRAYS - SELECTION / INDEXING

In [23]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d.shape

(3, 3)

In [26]:
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[2]

array([35, 40, 45])

In [28]:
arr_2d[1][1]

25

In [29]:
arr_2d[1, 1]

25

In [30]:
 arr_2d[0, 2]

15

In [31]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

### CONDITIONAL SELECTION

In [33]:
arr = np.arange(1, 11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr > 4

In [37]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

### NUMPY - ARRAY OPERATIONS

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
arr - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
arr.sum()

45

In [13]:
arr.mean()

4.5

In [14]:
arr.max()

9

In [16]:
arr.min()

0

In [17]:
arr.var() #Variance

8.25

In [18]:
arr.std() #Standard Deviation

2.8722813232690143

In [19]:
arr2d = np.arange(0, 25).reshape(5, 5)

In [22]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr2d.sum()

300

In [28]:
arr2d.sum(axis = 0) #Sum of Elements across the Rows | All new values of Rows are Added

array([50, 55, 60, 65, 70])

In [30]:
arr2d.sum(axis = 1) #Sum of Elements across the Columns All new values of Columns are Added

array([ 10,  35,  60,  85, 110])